### ISSUE TITLE
access to the parquet files

### ISSUE THREAD

**Issue by tcarval** [boom-lab/argo2parquet-public#1]
Hello Enrico, is there an access to the parquet files generated by argo2parquet ?

**Comment by enrico-mi** [comment]
Hi @tcarval , you can use the jupyter notebooks in the notebooks folder. They show how to read the generated parquet database. Unless you mean if there is a way to peak into each individual file like you would with a .csv or .txt file -- in which case you'd need some other tool that I am not aware of as they are binary files.
